<?php
/**
 * CheckoutStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CembraPay\RestApi\Model;
use \CembraPay\RestApi\ObjectSerializer;

/**
 * CheckoutStatus Class Doc Comment
 *
 * @category Class
 * @description List of possible checkout session statuses: - CREATED: checkout session created, response not yet sent back. - NOT-STARTED: checkout session exists, customer not yet redirected to CembraPay Checkout pages. - STARTED: customer is redirected to CembraPay Checkout pages but not yet finished checkout. - EXPIRED: checkout session is expired. - SUCCESS: transaction is authorized and customer redirected back to provided success url. - DECLINED: transaction is declined and customer redirected back to provided error url. - ERROR: error occured during customer checkout. In most error cases customer will be redirected to provided error url. - CANCELLED: checkout cancelled during customer checkout. Customer will be redirected to provided cancellation url.
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CheckoutStatus
{
    /**
     * Possible values of this enum
     */
    const CREATED = 'CREATED';
    const NOT_STARTED = 'NOT-STARTED';
    const STARTED = 'STARTED';
    const EXPIRED = 'EXPIRED';
    const SUCCESS = 'SUCCESS';
    const DECLINED = 'DECLINED';
    const ERROR = 'ERROR';
    const CANCELLED = 'CANCELLED';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED
            self::NOT_STARTED
            self::STARTED
            self::EXPIRED
            self::SUCCESS
            self::DECLINED
            self::ERROR
            self::CANCELLED
        ];
    }
}
