<?php
/**
 * CustAuth
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CembraPay\RestApi\Model;

use \ArrayAccess;
use \CembraPay\RestApi\ObjectSerializer;

/**
 * CustAuth Class Doc Comment
 *
 * @category Class
 * @description Details of Customer authentication.
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustAuth implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CustAuth';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'verified_email' => 'string',
        'email_verification_type' => '\CembraPay\RestApi\Model\ContactVerificationType',
        'verified_mobile' => 'string',
        'mobile_verification_type' => '\CembraPay\RestApi\Model\ContactVerificationType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'verified_email' => null,
        'email_verification_type' => null,
        'verified_mobile' => null,
        'mobile_verification_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'verified_email' => 'verifiedEmail',
        'email_verification_type' => 'emailVerificationType',
        'verified_mobile' => 'verifiedMobile',
        'mobile_verification_type' => 'mobileVerificationType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'verified_email' => 'setVerifiedEmail',
        'email_verification_type' => 'setEmailVerificationType',
        'verified_mobile' => 'setVerifiedMobile',
        'mobile_verification_type' => 'setMobileVerificationType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'verified_email' => 'getVerifiedEmail',
        'email_verification_type' => 'getEmailVerificationType',
        'verified_mobile' => 'getVerifiedMobile',
        'mobile_verification_type' => 'getMobileVerificationType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['verified_email'] = isset($data['verified_email']) ? $data['verified_email'] : null;
        $this->container['email_verification_type'] = isset($data['email_verification_type']) ? $data['email_verification_type'] : null;
        $this->container['verified_mobile'] = isset($data['verified_mobile']) ? $data['verified_mobile'] : null;
        $this->container['mobile_verification_type'] = isset($data['mobile_verification_type']) ? $data['mobile_verification_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets verified_email
     *
     * @return string
     */
    public function getVerifiedEmail()
    {
        return $this->container['verified_email'];
    }

    /**
     * Sets verified_email
     *
     * @param string $verified_email Verified email of the Customer
     *
     * @return $this
     */
    public function setVerifiedEmail($verified_email)
    {
        $this->container['verified_email'] = $verified_email;

        return $this;
    }

    /**
     * Gets email_verification_type
     *
     * @return \CembraPay\RestApi\Model\ContactVerificationType
     */
    public function getEmailVerificationType()
    {
        return $this->container['email_verification_type'];
    }

    /**
     * Sets email_verification_type
     *
     * @param \CembraPay\RestApi\Model\ContactVerificationType $email_verification_type email_verification_type
     *
     * @return $this
     */
    public function setEmailVerificationType($email_verification_type)
    {
        $this->container['email_verification_type'] = $email_verification_type;

        return $this;
    }

    /**
     * Gets verified_mobile
     *
     * @return string
     */
    public function getVerifiedMobile()
    {
        return $this->container['verified_mobile'];
    }

    /**
     * Sets verified_mobile
     *
     * @param string $verified_mobile Verified mobile phone of the Customer
     *
     * @return $this
     */
    public function setVerifiedMobile($verified_mobile)
    {
        $this->container['verified_mobile'] = $verified_mobile;

        return $this;
    }

    /**
     * Gets mobile_verification_type
     *
     * @return \CembraPay\RestApi\Model\ContactVerificationType
     */
    public function getMobileVerificationType()
    {
        return $this->container['mobile_verification_type'];
    }

    /**
     * Sets mobile_verification_type
     *
     * @param \CembraPay\RestApi\Model\ContactVerificationType $mobile_verification_type mobile_verification_type
     *
     * @return $this
     */
    public function setMobileVerificationType($mobile_verification_type)
    {
        $this->container['mobile_verification_type'] = $mobile_verification_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
