<?php
/**
 * DeliveryMethod
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CembraPay\RestApi\Model;
use \CembraPay\RestApi\ObjectSerializer;

/**
 * DeliveryMethod Class Doc Comment
 *
 * @category Class
 * @description List of possible delivery methods for goods, ordered by Customer: - POST: goods will be delivered by postal or other delivery company. - HLD: goods will be delivered by Merchant - employee of Merchant will phisically deliver goods to the Customer. - PICK-UP: goods will be delivered to &#x27;Box&#x27; or &#x27;Location&#x27; where ID of Customer cannot be verified. - SHOP: goods will be collected by Customer in Shop. - DIGITAL: goods are some digital product like sofware and will be delivered digitally via download or similar.
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DeliveryMethod
{
    /**
     * Possible values of this enum
     */
    const POST = 'POST';
    const HLD = 'HLD';
    const PICK_UP = 'PICK-UP';
    const SHOP = 'SHOP';
    const DIGITAL = 'DIGITAL';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::POST
            self::HLD
            self::PICK_UP
            self::SHOP
            self::DIGITAL
        ];
    }
}
