<?php
/**
 * RegistrationStatusResponseData
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CembraPay\RestApi\Model;

use \ArrayAccess;
use \CembraPay\RestApi\ObjectSerializer;

/**
 * RegistrationStatusResponseData Class Doc Comment
 *
 * @category Class
 * @description Status of registration session
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RegistrationStatusResponseData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RegistrationStatusResponseData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'registration_process_id' => 'string',
        'redirect_url_registration' => 'string',
        'registration_status' => '\CembraPay\RestApi\Model\RegistrationStatus',
        'registration_started_date_time' => '\DateTime',
        'token' => 'string',
        'transaction_status' => '\CembraPay\RestApi\Model\TransactionStatusResponseData'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'registration_process_id' => null,
        'redirect_url_registration' => null,
        'registration_status' => null,
        'registration_started_date_time' => 'date-time',
        'token' => 'uuid',
        'transaction_status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'registration_process_id' => 'registrationProcessId',
        'redirect_url_registration' => 'redirectUrlRegistration',
        'registration_status' => 'registrationStatus',
        'registration_started_date_time' => 'registrationStartedDateTime',
        'token' => 'token',
        'transaction_status' => 'transactionStatus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'registration_process_id' => 'setRegistrationProcessId',
        'redirect_url_registration' => 'setRedirectUrlRegistration',
        'registration_status' => 'setRegistrationStatus',
        'registration_started_date_time' => 'setRegistrationStartedDateTime',
        'token' => 'setToken',
        'transaction_status' => 'setTransactionStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'registration_process_id' => 'getRegistrationProcessId',
        'redirect_url_registration' => 'getRedirectUrlRegistration',
        'registration_status' => 'getRegistrationStatus',
        'registration_started_date_time' => 'getRegistrationStartedDateTime',
        'token' => 'getToken',
        'transaction_status' => 'getTransactionStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['registration_process_id'] = isset($data['registration_process_id']) ? $data['registration_process_id'] : null;
        $this->container['redirect_url_registration'] = isset($data['redirect_url_registration']) ? $data['redirect_url_registration'] : null;
        $this->container['registration_status'] = isset($data['registration_status']) ? $data['registration_status'] : null;
        $this->container['registration_started_date_time'] = isset($data['registration_started_date_time']) ? $data['registration_started_date_time'] : null;
        $this->container['token'] = isset($data['token']) ? $data['token'] : null;
        $this->container['transaction_status'] = isset($data['transaction_status']) ? $data['transaction_status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets registration_process_id
     *
     * @return string
     */
    public function getRegistrationProcessId()
    {
        return $this->container['registration_process_id'];
    }

    /**
     * Sets registration_process_id
     *
     * @param string $registration_process_id Unique identifier of Registration session. Required for RST requests.
     *
     * @return $this
     */
    public function setRegistrationProcessId($registration_process_id)
    {
        $this->container['registration_process_id'] = $registration_process_id;

        return $this;
    }

    /**
     * Gets redirect_url_registration
     *
     * @return string
     */
    public function getRedirectUrlRegistration()
    {
        return $this->container['redirect_url_registration'];
    }

    /**
     * Sets redirect_url_registration
     *
     * @param string $redirect_url_registration URL that must be used for redirecting customer to CembraPay Registration pages.
     *
     * @return $this
     */
    public function setRedirectUrlRegistration($redirect_url_registration)
    {
        $this->container['redirect_url_registration'] = $redirect_url_registration;

        return $this;
    }

    /**
     * Gets registration_status
     *
     * @return \CembraPay\RestApi\Model\RegistrationStatus
     */
    public function getRegistrationStatus()
    {
        return $this->container['registration_status'];
    }

    /**
     * Sets registration_status
     *
     * @param \CembraPay\RestApi\Model\RegistrationStatus $registration_status registration_status
     *
     * @return $this
     */
    public function setRegistrationStatus($registration_status)
    {
        $this->container['registration_status'] = $registration_status;

        return $this;
    }

    /**
     * Gets registration_started_date_time
     *
     * @return \DateTime
     */
    public function getRegistrationStartedDateTime()
    {
        return $this->container['registration_started_date_time'];
    }

    /**
     * Sets registration_started_date_time
     *
     * @param \DateTime $registration_started_date_time DateTime of registration session creation. ISO8601 Date with time in format 'yyyy-MM-ddTHH:mm:ssZ'.
     *
     * @return $this
     */
    public function setRegistrationStartedDateTime($registration_started_date_time)
    {
        $this->container['registration_started_date_time'] = $registration_started_date_time;

        return $this;
    }

    /**
     * Gets token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string $token Token can be provided instead or together with Customer details in SCR, AUT or CHK requests.
     *
     * @return $this
     */
    public function setToken($token)
    {
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets transaction_status
     *
     * @return \CembraPay\RestApi\Model\TransactionStatusResponseData
     */
    public function getTransactionStatus()
    {
        return $this->container['transaction_status'];
    }

    /**
     * Sets transaction_status
     *
     * @param \CembraPay\RestApi\Model\TransactionStatusResponseData $transaction_status transaction_status
     *
     * @return $this
     */
    public function setTransactionStatus($transaction_status)
    {
        $this->container['transaction_status'] = $transaction_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
