<?php
/**
 * SettlementProcessingStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CembraPay\RestApi\Model;
use \CembraPay\RestApi\ObjectSerializer;

/**
 * SettlementProcessingStatus Class Doc Comment
 *
 * @category Class
 * @description Processing status of the request - shows outcome of the operation. Possible values are also dependent on type of the Request.  List of possible processing statuses: - SETTLED:  returned when authorization amount is fully used and no more settlements possible. - PARTIALLY-SETTLED: returned when authorization amount is not fully used and another settlements are possible. - ERROR: returned in case, when error occures during request processing.
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SettlementProcessingStatus
{
    /**
     * Possible values of this enum
     */
    const SETTLED = 'SETTLED';
    const PARTIALLY_SETTLED = 'PARTIALLY-SETTLED';
    const ERROR = 'ERROR';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SETTLED
            self::PARTIALLY_SETTLED
            self::ERROR
        ];
    }
}
