<?php
/**
 * CancellationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * CancellationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CancellationRequest
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CancellationRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CancellationRequest"
     */
    public function testCancellationRequest()
    {
    }

    /**
     * Test attribute "request_msg_id"
     */
    public function testPropertyRequestMsgId()
    {
    }

    /**
     * Test attribute "request_msg_date_time"
     */
    public function testPropertyRequestMsgDateTime()
    {
    }

    /**
     * Test attribute "idempotency_key"
     */
    public function testPropertyIdempotencyKey()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "merchant_order_ref"
     */
    public function testPropertyMerchantOrderRef()
    {
    }

    /**
     * Test attribute "msg_extensions"
     */
    public function testPropertyMsgExtensions()
    {
    }

    /**
     * Test attribute "is_full_cancelation"
     */
    public function testPropertyIsFullCancelation()
    {
    }

    /**
     * Test attribute "psp_transaction_id"
     */
    public function testPropertyPspTransactionId()
    {
    }

    /**
     * Test attribute "settlement_details"
     */
    public function testPropertySettlementDetails()
    {
    }
}
