<?php
/**
 * CheckoutStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * CheckoutStatusTest Class Doc Comment
 *
 * @category    Class
 * @description List of possible checkout session statuses: - CREATED: checkout session created, response not yet sent back. - NOT-STARTED: checkout session exists, customer not yet redirected to CembraPay Checkout pages. - STARTED: customer is redirected to CembraPay Checkout pages but not yet finished checkout. - EXPIRED: checkout session is expired. - SUCCESS: transaction is authorized and customer redirected back to provided success url. - DECLINED: transaction is declined and customer redirected back to provided error url. - ERROR: error occured during customer checkout. In most error cases customer will be redirected to provided error url. - CANCELLED: checkout cancelled during customer checkout. Customer will be redirected to provided cancellation url.
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckoutStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CheckoutStatus"
     */
    public function testCheckoutStatus()
    {
    }
}
