<?php
/**
 * CheckoutStatusResponseDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * CheckoutStatusResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description Status of checkout session
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckoutStatusResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CheckoutStatusResponseData"
     */
    public function testCheckoutStatusResponseData()
    {
    }

    /**
     * Test attribute "checkout_process_id"
     */
    public function testPropertyCheckoutProcessId()
    {
    }

    /**
     * Test attribute "redirect_url_checkout"
     */
    public function testPropertyRedirectUrlCheckout()
    {
    }

    /**
     * Test attribute "checkout_status"
     */
    public function testPropertyCheckoutStatus()
    {
    }

    /**
     * Test attribute "checkout_started_date_time"
     */
    public function testPropertyCheckoutStartedDateTime()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "transaction_status"
     */
    public function testPropertyTransactionStatus()
    {
    }
}
