<?php
/**
 * ConsentProvidingChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * ConsentProvidingChannelTest Class Doc Comment
 *
 * @category    Class
 * @description List of possible Consent providing channels:  - MERCHANT: consent collected by Merchant in Merchant web shop. Usually by additions in Merchants Shop terms and conditions. - MERCHANT-POS: consent collected at Merchants Pos - CEMBRAPAY-CHECKOUT: consent collected via CembraPay Checkout UI - CEMBRAPAY-REGISTRATION: consent collected via CembraPay Registration UI - AFFILIATE: consent collected by affiliate - OTHER: other way of collecting consent
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsentProvidingChannelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ConsentProvidingChannel"
     */
    public function testConsentProvidingChannel()
    {
    }
}
