<?php
/**
 * CustDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * CustDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description Details of the Customer.  Depending on Customer Type some fields are mandatory and some are not expected. For example CompanyName is not expected if type of Customer is &#x27;P&#x27; (person).
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustDetails"
     */
    public function testCustDetails()
    {
    }

    /**
     * Test attribute "merchant_cust_ref"
     */
    public function testPropertyMerchantCustRef()
    {
    }

    /**
     * Test attribute "logged_in"
     */
    public function testPropertyLoggedIn()
    {
    }

    /**
     * Test attribute "cust_type"
     */
    public function testPropertyCustType()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "date_of_birth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "is_above18"
     */
    public function testPropertyIsAbove18()
    {
    }

    /**
     * Test attribute "salutation"
     */
    public function testPropertySalutation()
    {
    }

    /**
     * Test attribute "company_reg_num"
     */
    public function testPropertyCompanyRegNum()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "company_department"
     */
    public function testPropertyCompanyDepartment()
    {
    }

    /**
     * Test attribute "doc_type"
     */
    public function testPropertyDocType()
    {
    }

    /**
     * Test attribute "doc_issuer"
     */
    public function testPropertyDocIssuer()
    {
    }

    /**
     * Test attribute "doc_nr"
     */
    public function testPropertyDocNr()
    {
    }

    /**
     * Test attribute "doc_valid_till"
     */
    public function testPropertyDocValidTill()
    {
    }

    /**
     * Test attribute "permit_type"
     */
    public function testPropertyPermitType()
    {
    }

    /**
     * Test attribute "in_switzerland_since"
     */
    public function testPropertyInSwitzerlandSince()
    {
    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {
    }
}
