<?php
/**
 * CustAuthTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * CustAuthTest Class Doc Comment
 *
 * @category    Class
 * @description Details of Customer authentication.
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustAuthTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustAuth"
     */
    public function testCustAuth()
    {
    }

    /**
     * Test attribute "verified_email"
     */
    public function testPropertyVerifiedEmail()
    {
    }

    /**
     * Test attribute "email_verification_type"
     */
    public function testPropertyEmailVerificationType()
    {
    }

    /**
     * Test attribute "verified_mobile"
     */
    public function testPropertyVerifiedMobile()
    {
    }

    /**
     * Test attribute "mobile_verification_type"
     */
    public function testPropertyMobileVerificationType()
    {
    }
}
