<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description Details about Order.
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "basket_items_google_taxonomies"
     */
    public function testPropertyBasketItemsGoogleTaxonomies()
    {
    }

    /**
     * Test attribute "basket_items_prices"
     */
    public function testPropertyBasketItemsPrices()
    {
    }

    /**
     * Test attribute "downpayment_to_merchant_amount"
     */
    public function testPropertyDownpaymentToMerchantAmount()
    {
    }

    /**
     * Test attribute "subscription_type"
     */
    public function testPropertySubscriptionType()
    {
    }

    /**
     * Test attribute "payout_info"
     */
    public function testPropertyPayoutInfo()
    {
    }
}
