<?php
/**
 * RegistrationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * RegistrationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description RegistrationRequest
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RegistrationRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RegistrationRequest"
     */
    public function testRegistrationRequest()
    {
    }

    /**
     * Test attribute "request_msg_id"
     */
    public function testPropertyRequestMsgId()
    {
    }

    /**
     * Test attribute "request_msg_date_time"
     */
    public function testPropertyRequestMsgDateTime()
    {
    }

    /**
     * Test attribute "idempotency_key"
     */
    public function testPropertyIdempotencyKey()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "cust_details"
     */
    public function testPropertyCustDetails()
    {
    }

    /**
     * Test attribute "cembra_pay_details"
     */
    public function testPropertyCembraPayDetails()
    {
    }

    /**
     * Test attribute "merchant_details"
     */
    public function testPropertyMerchantDetails()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "psp_transaction_id"
     */
    public function testPropertyPspTransactionId()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "merchant_order_ref"
     */
    public function testPropertyMerchantOrderRef()
    {
    }

    /**
     * Test attribute "cust_auth"
     */
    public function testPropertyCustAuth()
    {
    }

    /**
     * Test attribute "billing_addr"
     */
    public function testPropertyBillingAddr()
    {
    }

    /**
     * Test attribute "delivery_details"
     */
    public function testPropertyDeliveryDetails()
    {
    }

    /**
     * Test attribute "cust_contacts"
     */
    public function testPropertyCustContacts()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "session_info"
     */
    public function testPropertySessionInfo()
    {
    }

    /**
     * Test attribute "customer_consents"
     */
    public function testPropertyCustomerConsents()
    {
    }

    /**
     * Test attribute "msg_extensions"
     */
    public function testPropertyMsgExtensions()
    {
    }
}
