<?php
/**
 * RequestMsgTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * RequestMsgTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Check suitable value for your request (see request description): - SCR: screening request. - AUT: authorization request. Can be with immediate settlement. - REG: registration request. Starts registration session. - CHK: checkout request. Starts checkout session. - SET: settlement request. - CAN: cancellation request. Cancels unsettled amount partly or fully. - CNT: credit note request. Cancels settled amount partly or fully. - TKL: token lookup request. - TST: transaction status request. - RST: registration status request. - CST: checkout status request. - CFM: authorization confirmation request.
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestMsgTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RequestMsgType"
     */
    public function testRequestMsgType()
    {
    }
}
