<?php
/**
 * ScreeningCustomerConsentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * ScreeningCustomerConsentTest Class Doc Comment
 *
 * @category    Class
 * @description List of Customer consents. Mandatory for SCR requests. Please reflect the Data Submission to CembraPay in your Data Privacy Statement or T&amp;Cs
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScreeningCustomerConsentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScreeningCustomerConsent"
     */
    public function testScreeningCustomerConsent()
    {
    }

    /**
     * Test attribute "consent_type"
     */
    public function testPropertyConsentType()
    {
    }

    /**
     * Test attribute "consent_provided_at"
     */
    public function testPropertyConsentProvidedAt()
    {
    }

    /**
     * Test attribute "consent_date"
     */
    public function testPropertyConsentDate()
    {
    }

    /**
     * Test attribute "consent_reference"
     */
    public function testPropertyConsentReference()
    {
    }
}
