<?php
/**
 * ScreeningResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CembraPay\RestApi;

use PHPUnit\Framework\TestCase;

/**
 * ScreeningResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ScreeningResponse
 * @package     CembraPay\RestApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScreeningResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScreeningResponse"
     */
    public function testScreeningResponse()
    {
    }

    /**
     * Test attribute "request_msg_id"
     */
    public function testPropertyRequestMsgId()
    {
    }

    /**
     * Test attribute "request_msg_date_time"
     */
    public function testPropertyRequestMsgDateTime()
    {
    }

    /**
     * Test attribute "reply_msg_id"
     */
    public function testPropertyReplyMsgId()
    {
    }

    /**
     * Test attribute "reply_msg_date_time"
     */
    public function testPropertyReplyMsgDateTime()
    {
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
    }

    /**
     * Test attribute "idempotency_key"
     */
    public function testPropertyIdempotencyKey()
    {
    }

    /**
     * Test attribute "request_merchant_id"
     */
    public function testPropertyRequestMerchantId()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "merchant_cust_ref"
     */
    public function testPropertyMerchantCustRef()
    {
    }

    /**
     * Test attribute "merchant_order_ref"
     */
    public function testPropertyMerchantOrderRef()
    {
    }

    /**
     * Test attribute "processing_status"
     */
    public function testPropertyProcessingStatus()
    {
    }

    /**
     * Test attribute "screening_details"
     */
    public function testPropertyScreeningDetails()
    {
    }
}
