<?php
/**
 * TransactionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.66
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CembraPay\RestApi;

use CembraPay\RestApi\Configuration;
use CembraPay\RestApi\ApiException;
use CembraPay\RestApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1TransactionsAuthorizePost
     *
     * Authorization request.
     *
     */
    public function testV1TransactionsAuthorizePost()
    {
    }

    /**
     * Test case for v1TransactionsCancelPost
     *
     * Cancelation request.
     *
     */
    public function testV1TransactionsCancelPost()
    {
    }

    /**
     * Test case for v1TransactionsConfirmPost
     *
     * Confirmation request.
     *
     */
    public function testV1TransactionsConfirmPost()
    {
    }

    /**
     * Test case for v1TransactionsCreditPost
     *
     * Credit request.
     *
     */
    public function testV1TransactionsCreditPost()
    {
    }

    /**
     * Test case for v1TransactionsSettlePost
     *
     * Settlement request.
     *
     */
    public function testV1TransactionsSettlePost()
    {
    }

    /**
     * Test case for v1TransactionsStatusPost
     *
     * Get Status request.
     *
     */
    public function testV1TransactionsStatusPost()
    {
    }

    /**
     * Test case for v1TransactionsTokenPost
     *
     * Get Token request.
     *
     */
    public function testV1TransactionsTokenPost()
    {
    }
}
