<?php
/**
 * TransactionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Transactions Gateway Microservice API
 *
 * Public JSON API integration and operations
 *
 * OpenAPI spec version: 1.0
 * Contact: integration@cembrapay.ch
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.62
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CembraPay\RestApi;

use CembraPay\RestApi\Configuration;
use CembraPay\RestApi\ApiException;
use CembraPay\RestApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  CembraPay\RestApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for vversionTransactionsAuthorizePost
     *
     * Authorization request.
     *
     */
    public function testVversionTransactionsAuthorizePost()
    {
    }

    /**
     * Test case for vversionTransactionsCancelPost
     *
     * Cancelation request.
     *
     */
    public function testVversionTransactionsCancelPost()
    {
    }

    /**
     * Test case for vversionTransactionsConfirmPost
     *
     * Confirmation request.
     *
     */
    public function testVversionTransactionsConfirmPost()
    {
    }

    /**
     * Test case for vversionTransactionsCreditPost
     *
     * Credit request.
     *
     */
    public function testVversionTransactionsCreditPost()
    {
    }

    /**
     * Test case for vversionTransactionsSettlePost
     *
     * Settlement request.
     *
     */
    public function testVversionTransactionsSettlePost()
    {
    }

    /**
     * Test case for vversionTransactionsStatusPost
     *
     * Get Status request.
     *
     */
    public function testVversionTransactionsStatusPost()
    {
    }

    /**
     * Test case for vversionTransactionsTokenPost
     *
     * Get Token request.
     *
     */
    public function testVversionTransactionsTokenPost()
    {
    }
}
